#ifndef DSVIEW_CLI_DSL_LAYOUT_H
#define DSVIEW_CLI_DSL_LAYOUT_H

#define DSL_HEADER_FORMAT_VERSION 3
#define DSL_SESSION_FORMAT_VERSION 3
#define DSL_LOGIC_BLOCK_SAMPLES (1ULL << 24)
#define DSL_LOGIC_BLOCK_BYTES (DSL_LOGIC_BLOCK_SAMPLES / 8ULL)

#endif
